services:
  cms-aminah-jaya:
    image: cms-aminah-jaya:latest
    container_name: cms-aminah-jaya
    restart: always
    ports:
      - "${HOST_PORT:-3001}:${HOST_PORT:-3001}"
    environment:
      - NODE_ENV=production
      - ORIGIN=http://${VPS_IP:-103.103.20.58}:${HOST_PORT:-3001}
      - NITRO_URL=http://${VPS_IP:-103.103.20.58}:${HOST_PORT:-3001}
      - PROTOCOL=http
      - HOST=0.0.0.0
      - PORT=${HOST_PORT:-3001}
      - VITE_API_BASE=${VITE_API_BASE}
