services:
  storefront-aminah-jaya:
    image: storefront-aminah-jaya:latest
    container_name: storefront-aminah-jaya
    restart: always
    ports:
      - "${HOST_PORT:-3002}:${HOST_PORT:-3002}"
    environment:
      - NODE_ENV=production
      - ORIGIN=http://${VPS_IP:-103.103.20.58}:${HOST_PORT:-3002}
      - NITRO_URL=http://${VPS_IP:-103.103.20.58}:${HOST_PORT:-3002}
      - PROTOCOL=http
      - HOST=0.0.0.0
      - PORT=${HOST_PORT:-3002}
      - VITE_API_URL=${VITE_API_URL}
      - VITE_API_BASE=${VITE_API_BASE}
      - VITE_GOOGLE_CLIENT_ID=${VITE_GOOGLE_CLIENT_ID}
      - VITE_INTEGRASI_API_BASE=${VITE_INTEGRASI_API_BASE}

